### ISSUE TITLE
Frames indexes

### ISSUE THREAD

**Issue by bguetarni** [epic-kitchens/epic-kitchens-100-annotations#11]
Hi, thanks a lot for sharing such a dataset !
I would like to know if the *start_frame* and *stop_frame* in **EPIC_100_train.csv<sup>1</sup>** are the position of the images in the video folder or rather the number in the images name (e:g: frame_0000065750.jpg).

I'm asking this because I found two videos where the labels are misleading, P08_05 and P08_17.
When looking at the line 28006 in **(1)** the start_frame is 66111, however there a total of 65768 images in the P08_05 folder, so it cannot be its position. But there is no file named frame_66111.jpg neither. And the same thing occur with P08_17. All the other videos are ok.

Am I missing something somewhere ?
Thanks

**Comment by dimadamen** [comment]
There seems to be an issue with your downloading scripts. Maybe your download failed and you didn't get the full set of images?

In P08_05, I can confirm there's 105232 frames. So maybe you didn't download or extract the .tar files correctly.

You should be able to find the frames specified (e.g. 66111). I suggest re-downloading or re-uncompressing.

This issue is now closed.

**Comment by edessa** [comment]
I'm running into an issue where for a couple videos, the later the frame index, the more often the action segment annotations are wholly unaligned with the action annotations. For example, for the annotations of video P01_109, early on the action annotations are very accurate, but looking at say, frame 180,000 we see that none of the actions surrounding that timestamp in the CSV file are remotely close to what happens in the folder of rgb frames. It seems there is an issue temporally aligning the RGB frames with the action segment annotations. My download folder for P01_109 has 222K frames, for reference. Is there something wrong with how I'm downloading things, or maybe this is a versioning issue?

Thank you so much!!

**Comment by dimadamen** [comment]
Your problem is related to an erratum we published regarding the frame extractions for two videos: P01_109.MP4 and P27_103.MP4

Please go to: https://github.com/epic-kitchens/epic-kitchens-100-annotations/blob/master/README.md#erratum

The third title in the page “Erratum” advises you how to download the corrected frames for these two videos.

Apologies for any inconvenience. Let us know if this does not solve your problem.

On 14 Jan 2021, at 18:50, Eadom Dessalene <notifications@github.com<mailto:notifications@github.com>> wrote:



I'm running into an issue where for a couple videos, the later the frame index, the more often the action segment annotations are wholly unaligned with the action annotations. For example, for the annotations of video P01_109, early on the action annotations are very accurate, but looking at say, frame 180,000 we see that none of the actions surrounding that timestamp in the CSV file are remotely close to what happens in the folder of rgb frames. It seems there is an issue temporally aligning the RGB frames with the action segment annotations. My download folder for P01_109 has 222K frames, for reference. Is there something wrong with how I'm downloading things, or maybe this is a versioning issue?

Thank you so much!!

**Comment by edessa** [comment]
My mistake, I had skipped that section thinking it was related to the computation of the flow frames. Thank you so much!!

**Comment by edessa** [comment]
The hardware acceleration (hwaccel) flag in the ffmpeg command from the Erratum isn't supported by my GPU, meaning my command is slightly different. For consistencies sake, could anyone confirm the overall number of frames the P01_109 folder should have? Thank you!!

**Comment by dimadamen** [comment]
Sorry this was difficult for you. You can directly download all the corrected frames from dropbox by following this link:
https://www.dropbox.com/sh/wp2pqib2nsvv4hg/AADpghTW8fIZ9nOI0ueeDGOYa?dl=0

I can also confirm, for your convenience, that P01_109 contains 185406 frames.

**Comment by edessa** [comment]
Thank you so much!!
