### ISSUE TITLE
Samples that should have been split up

### ISSUE THREAD

**Issue by jdevoldere** [epic-kitchens/epic-kitchens-100-annotations#3]
Consider the following sample:

> P21_04_67,P21,P21_04,00:08:34.779,00:08:31.97,00:08:33.21,30718,30792,placing tortillas on table and yoghurt on the table and milk on the table,place-on,1,tortilla,107,"['tortilla', 'table', 'yoghurt', 'table', 'milk', 'table']","[107, 42, 98, 42, 64, 42]"

This sample should have been split up into 3 different actions.

I think virtually all samples with more than 3 noun classes make a similar mistake

**Comment by mwray** [comment]
Hi,

Thanks for your interest in our dataset! When we were doing the parsing for the dataset we have the assumption that an action consists of a single verb applied to one or more nouns. In most cases we found that this was perfectly reasonable. The key problem here is due to the multitude of `ands` between objects within the narration which makes it sound like multiple different actions.

I looked at all examples within the dataset with more than three nouns (65 narrations out of 90,141) and find that in the majority of cases the sentences are fine (e.g. `slide cherry tomato halves from chopping board into pan using knife`) and only one other narration (`put plates and knives and forks on plate`) runs into this same issue.

Having just released the dataset and with challenges forthcoming, we would prefer to make minimal changes to the narrations and the parsing. But we might look at this assumption in the future if we find it is a problem.

Thanks,

Mike
