### ISSUE TITLE
Corrupted Videos

### ISSUE THREAD

**Issue by ADiko1997** [epic-kitchens/epic-kitchens-100-annotations#33]
Many videos from the EK100 validation set are corrupted. Some examples that I found are: 
P26_35, P22_03, P22_01, P18_09, P12_03, P10_03,  P02_12 and P01_14. I guess those are related also to EK55.

**Comment by dimadamen** [comment]
That is not true... where did you download the videos from?
This is where the videos are stored: https://data.bris.ac.uk/data/dataset/3h91syskeag572hl6tvuovwv4d
You can even watch these on the server and see they are not corrupted and download them correctly.

**Comment by ADiko1997** [comment]
Hello,
I used the download script form the repo.
I tried to download it several times. I can give it another shot and see if
it works.
Kind regards
Anxhelo

**Comment by dimadamen** [comment]
For example, P26_35 you noted above is available directly here:
https://data.bris.ac.uk/datasets/3h91syskeag572hl6tvuovwv4d/videos/test/P26/P26_35.MP4
You can see it's not corrupted.

**Comment by dimadamen** [comment]
At times your connection resets and stops the download. This is probably an issue at your end, not with the script or the files.

**Comment by ADiko1997** [comment]
I will download them again.
Thank you very much

**Comment by ADiko1997** [comment]
Ok, i will download all the mentioned videos 1 by 1.
Kind regards

**Comment by ADiko1997** [comment]
Okay, so I tried to download P26_35, and it works, probably a connection error. However, there are other cases in which I am having an issue. Right now, I am downloading them all again, and if the issue is not resolved, I will report them here. P.s. most cases seem related to the test set of ek55.
Thank you

**Comment by dimadamen** [comment]
Some files are significantly larger than others. Ensure your network does not have a timeout restriction,

**Comment by ADiko1997** [comment]
Sure, I ll do that. Thank you.

**Comment by ADiko1997** [comment]
Ok, so i tried the following videos P26_30 (56MB) P26_32 (295MB)  P26_34.MP4 (386 MB)  P26_36 (755MB)  P26_39 (205MB)    P26_40 (252MB)  P26_41 (420MB) downloaded using the official script with arguments --videos --specific-videos .... and files are corrupted, IDK if it is an error of mine but in the past i have tried again these files and i cant seem to have a sane version of them.

**Comment by dimadamen** [comment]
E.g. P26_30 should be 58.3MB, and you can see by getting the direct link: 
https://data.bris.ac.uk/datasets/3h91syskeag572hl6tvuovwv4d/videos/test/P26/P26_30.MP4
that indeed it's not corrupted.

Unfortunately it is difficult to debug what is wrong with your connection, but the dataset has been downloaded using these scripts 100s of times. So unfortunately I can only confirm the problem is neither with the script nor with the files. It's with your connection.

You can try to download the tar files directly from the university links here: https://data.bris.ac.uk/data/dataset/ccc55bf0b2cad7f754ad303e03bbdfb7 or via academic torrents, avoiding the script.

**Comment by ADiko1997** [comment]
Thank you, I will find a way around to download them from the torrent.
Kind regrads
